/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace PaddleThrift
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class GameStart : TBase
  {
    private long _serverTime;
    private double _ballDisplacementX;
    private double _ballDisplacementY;
    private int _playerId;

    public long ServerTime
    {
      get
      {
        return _serverTime;
      }
      set
      {
        __isset.serverTime = true;
        this._serverTime = value;
      }
    }

    public double BallDisplacementX
    {
      get
      {
        return _ballDisplacementX;
      }
      set
      {
        __isset.ballDisplacementX = true;
        this._ballDisplacementX = value;
      }
    }

    public double BallDisplacementY
    {
      get
      {
        return _ballDisplacementY;
      }
      set
      {
        __isset.ballDisplacementY = true;
        this._ballDisplacementY = value;
      }
    }

    public int PlayerId
    {
      get
      {
        return _playerId;
      }
      set
      {
        __isset.playerId = true;
        this._playerId = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool serverTime;
      public bool ballDisplacementX;
      public bool ballDisplacementY;
      public bool playerId;
    }

    public GameStart() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64) {
              ServerTime = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Double) {
              BallDisplacementX = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Double) {
              BallDisplacementY = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I32) {
              PlayerId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("GameStart");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.serverTime) {
        field.Name = "serverTime";
        field.Type = TType.I64;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(ServerTime);
        oprot.WriteFieldEnd();
      }
      if (__isset.ballDisplacementX) {
        field.Name = "ballDisplacementX";
        field.Type = TType.Double;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(BallDisplacementX);
        oprot.WriteFieldEnd();
      }
      if (__isset.ballDisplacementY) {
        field.Name = "ballDisplacementY";
        field.Type = TType.Double;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(BallDisplacementY);
        oprot.WriteFieldEnd();
      }
      if (__isset.playerId) {
        field.Name = "playerId";
        field.Type = TType.I32;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(PlayerId);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("GameStart(");
      sb.Append("ServerTime: ");
      sb.Append(ServerTime);
      sb.Append(",BallDisplacementX: ");
      sb.Append(BallDisplacementX);
      sb.Append(",BallDisplacementY: ");
      sb.Append(BallDisplacementY);
      sb.Append(",PlayerId: ");
      sb.Append(PlayerId);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
