/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace PaddleThrift
{
  public enum MessageId
  {
    GAME_START = 0,
    ENTITY_POSITION = 1,
    POINTS_UPDATE = 2,
    GAME_OVER = 3,
  }
}
