/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace PaddleThrift
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class PointsUpdate : TBase
  {
    private int _playerOneScore;
    private int _playerTwoScore;

    public int PlayerOneScore
    {
      get
      {
        return _playerOneScore;
      }
      set
      {
        __isset.playerOneScore = true;
        this._playerOneScore = value;
      }
    }

    public int PlayerTwoScore
    {
      get
      {
        return _playerTwoScore;
      }
      set
      {
        __isset.playerTwoScore = true;
        this._playerTwoScore = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool playerOneScore;
      public bool playerTwoScore;
    }

    public PointsUpdate() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              PlayerOneScore = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              PlayerTwoScore = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("PointsUpdate");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.playerOneScore) {
        field.Name = "playerOneScore";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(PlayerOneScore);
        oprot.WriteFieldEnd();
      }
      if (__isset.playerTwoScore) {
        field.Name = "playerTwoScore";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(PlayerTwoScore);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("PointsUpdate(");
      sb.Append("PlayerOneScore: ");
      sb.Append(PlayerOneScore);
      sb.Append(",PlayerTwoScore: ");
      sb.Append(PlayerTwoScore);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
